const config = {
    env: "https://webservice.guidemapper.com:8081",
    login_url: "https://webservice.guidemapper.com:8081/login",
    sign_in_url: "https://webservice.guidemapper.com:8081/signin",
    cadastro_url: "https://webservice.guidemapper.com:8081/point",
    gerar_geo_file_url:"https://webservice.guidemapper.com:8081/gerarArquivoParaMapa",
    gerar_arquivo_to_aprove_url: "https://webservice.guidemapper.com:8081/gerarArquivoAprovacao",
    end_point_url: "https://webservice.guidemapper.com:8081",
    get_user: "https://webservice.guidemapper.com:8081/user/",
    forget_password: "https://webservice.guidemapper.com:8081/user/forget",
    reset_url: "https://webservice.guidemapper.com:8081/user/reset_password",
    test_token: "https://webservice.guidemapper.com:8081/token",
    list_points_by_user: "https://webservice.guidemapper.com:8081/point/users?userId=",
    update_point: "https://webservice.guidemapper.com:8081/v2/point?pointId=",
    translate_point: "https://webservice.guidemapper.com:8081/v2/point/translate?pointId=",
    get_routes_endpoint: "/routes?",
}